name: test

on:
  push:
    branches: [master, develop]
    
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonando repositorio
        uses: actions/checkout@v2
        
      - name: Configurando ambiente java
        uses: actions/setup-java@v2
        with:
          java-version: 11
      
      - name: Instalando dependencias e rodando testes
        run: |
          mvn clean package install
